server:
  port: 82
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        healthCheckPath: ${management.context-path}/consul/health
        healthCheckInterval: 10s
        heartbeat:
          enabled: true
  application:
    name: cloud-consumer-service-order-82