server:
  port: 9100
spring:
  application:
    name: cloud-seata-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 #默认8719，被占用的话会自动向8720后进行扫描
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false