server:
  port: 9527
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
      routes:
        - id: url-proxy-1
          uri: lb://cloud-payment-service-consul-hystrix
          predicates:
            - Path=/v1/api/pay/** # 断言，路径匹配的进行路由
        - id: url-proxy-2
          uri: https://skwen-blog.baklib-free.com/
          predicates:
            - Path=/** # 断言，路径匹配的进行路由
            #- After=#可以通过ZonedDateTime.now()获得
            #- Cookie=token#是否一定要有指定cookie才能访问
            #- Header=token, [\S] #是否一定要有指定cookie才能访问
            #其他详细配置参考：https://blog.csdn.net/qq_38380025/article/details/102968559
    #      routes:
    #        - id: url-proxy-1
    #          uri: http://localhost:8008
    #          predicates:
    #            - Path=/v1/api/pay/** # 断言，路径匹配的进行路由
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        healthCheckPath: ${management.context-path}/consul/health
        healthCheckInterval: 10s
        heartbeat:
          enabled: true
  application:
    name: cloud-gateway-gateway-9527