server:
  port: 86
spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 #默认8719，被占用的话会自动向8720后进行扫描
ribbon:
  #处理请求的超时时间，5秒
  ReadTimeout:  5000
  #连接建立的超时时长，5秒
  ConnectTimeout: 5000
  #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetries: 1
  #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  MaxAutoRetriesNextServer: 0
  #/是否对所有操作都重试，默认false
  OkToRetryOnAllOperations: false

#开启openFeign日志输出功能
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cloud.springcloud.service.PaymentFeignService: debug

#对Feign的支持
feign:
  sentinel:
    enabled: true