server:
  port: 85
spring:
  application:
    name: cloud-consumer-order-85
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848
service-url:
  nacos-user-service: http://cloud-payment-service-nacos/v1/api #用于RestTemplate在controller中进行读取，方便修改

ribbon:
  #处理请求的超时时间，5秒
  ReadTimeout:  5000
  #连接建立的超时时长，5秒
  ConnectTimeout: 5000
  #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetries: 1
  #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  MaxAutoRetriesNextServer: 0
  #/是否对所有操作都重试，默认false
  OkToRetryOnAllOperations: false

#开启openFeign日志输出功能
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cloud.springcloud.service.PaymentFeignService: debug